### ISSUE TITLE
Update laptop software to 2021

### ISSUE THREAD

**Issue by SHS-Programmers** [StaleyRobotics/StaleyRC2021#23]
Start here and update all the stuff https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/frc-game-tools.html

**Comment by Dustin-Klein** [comment]
@AkashaSnow @bobtheragelot @Landon924  Make sure to leave a comment here on the issue describing what you have done.

So for this it would be something like:
"Updated to the latest version of National Instruments and got the most recent versions of all WPI software."

Or for the updating the RIOs ticket it would be like:
"Updated 4 RoboRios to 2021 firmware"

**Comment by Dustin-Klein** [comment]
Thats just helpful to keep track of the work that is finished
